export const ACCOUNT_SET_TOKEN = "ACCOUNT_SET_TOKEN";
export const ACCOUNT_SET_USER = "ACCOUNT_SET_USER";
export const ACCOUNT_CLEAR = 'ACCOUNT_CLEAR';

export const PRODUCT_SET_NEWPRODUCT = 'PRODUCT_SET_NEWPRODUCT';
export const PRODUCT_SET_BESTSELLER = 'PRODUCT_SET_BESTSELLER';
export const PRODUCT_SET_PRODUCTS = 'PRODUCT_SET_PRODUCTS';
export const PRODUCT_CLEAR_PRODUCTS = 'PRODUCT_CLEAR_PRODUCTS'
export const PRODUCT_SET_CATEGORY_INDEX = 'PRODUCT_SET_CATEGORY_INDEX'
export const PRODUCT_SET_CATEGORIES = 'PRODUCT_SET_CATEGORIES'

export const CART_SET_CART = 'CART_SET_CART';
export const CART_SET_TOTAL = 'CART_SET_TOTAL';
export const CART_CLEAR = 'CART_CLEAR'

export const ADDRESS_SET_ADDRESSES = 'ADDRESS_SET_ADDRESSES';
export const ADDRESS_CLEAR = 'ADDRESS_CLEAR';

export const ORDER_SET_ORDER = 'ORDER_SET_ORDER';
export const ORDER_SET_PAGINATION = 'ORDER_SET_PAGINATION';
export const ORDER_CLEAR = 'ORDER_CLEAR';